fix: liberacion puerto en dast

diff --git a/.github/workflows/dast.yml b/.github/workflows/dast.yml
--- a/.github/workflows/dast.yml
+++ b/.github/workflows/dast.yml
@@ -1,12 +1,10 @@
 name: DAST Scan
 
 on:
-  workflow_call: 
-    inputs:
-      image-tag:
-        type: string
-        description: 'The name of the docker image to scan'
-        required: true
+  push:
+    branches:
+      - main
+      - dev
 
 jobs:
   dast-scan:
@@ -16,8 +14,15 @@ jobs:
       - name: Check out the repository
         uses: actions/checkout@v4
 
-      - name: Authenticate to Docker Hub
-        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+      - name: Free port 5006 if in use
+        run: |
+          echo "Verificando si el puerto 5006 está en uso..."
+          if lsof -i :5006; then
+            echo "Puerto 5006 en uso. Matando proceso..."
+            fuser -k 5006/tcp || true
+          else
+            echo "Puerto 5006 está libre."
+          fi
 
       - name: Build Docker image
         run: |
@@ -37,16 +42,16 @@ jobs:
       - name: Test container endpoint
         run: |
           echo "Verificando si el servicio responde en localhost:5006..."
-          for i in {1..30}; do
-              status=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5006)
-              if [ "$status" -eq 200 ]; then
-                  echo "El servicio está disponible."
-                  exit 0
-              fi
+          for i in {1..10}; do
+            if curl -s http://localhost:5006 > /dev/null; then
+              echo "El servicio está disponible."
+              exit 0
+            else
               echo "Intento $i: El servicio aún no está disponible, reintentando..."
               sleep 5
+            fi
           done
-          echo "Error: El servicio no respondió después de 30 intentos."
+          echo "Error: El servicio no respondió a tiempo."
           exit 1
 
       - name: ZAP Full Scan
